import { ApplicationStepConfig, ApplicationStepName } from '@/types';

export const APPLICATION_STEPS: ApplicationStepConfig[] = [
  {
    name: 'cv_screening',
    number: 1,
    title: 'CV Screening',
    description: 'Upload your CV and provide your professional background information.',
    fields: [
      {
        name: 'cv_summary',
        label: 'Professional Summary',
        type: 'textarea',
        required: true,
        placeholder: 'Briefly describe your professional background and key achievements...',
        helperText: 'Minimum 100 characters',
      },
      {
        name: 'linkedin_url',
        label: 'LinkedIn Profile URL',
        type: 'text',
        required: false,
        placeholder: 'https://linkedin.com/in/yourprofile',
      },
      {
        name: 'years_of_experience',
        label: 'Years of Relevant Experience',
        type: 'select',
        required: true,
        options: [
          { value: '0', label: 'No experience' },
          { value: '0-1', label: '0-1 years' },
          { value: '1-2', label: '1-2 years' },
          { value: '2-3', label: '2-3 years' },
          { value: '3+', label: '3+ years' },
        ],
      },
      {
        name: 'availability_date',
        label: 'Earliest Start Date',
        type: 'date',
        required: true,
        helperText: 'When can you start the internship?',
      },
    ],
    documents: [
      {
        name: 'cv',
        label: 'Curriculum Vitae (CV)',
        required: true,
        acceptedFormats: ['.pdf', '.doc', '.docx'],
        maxSize: 5,
        description: 'Upload your latest CV in PDF or Word format (max 5MB)',
      },
      {
        name: 'cover_letter',
        label: 'Cover Letter',
        required: true,
        acceptedFormats: ['.pdf', '.doc', '.docx'],
        maxSize: 3,
        description: 'Upload your cover letter (max 3MB)',
      },
    ],
  },
  {
    name: 'interview',
    number: 2,
    title: 'Interview',
    description: 'Provide information for scheduling your interview.',
    fields: [
      {
        name: 'preferred_interview_mode',
        label: 'Preferred Interview Mode',
        type: 'select',
        required: true,
        options: [
          { value: 'video', label: 'Video Call (Zoom/Meet)' },
          { value: 'phone', label: 'Phone Call' },
          { value: 'in-person', label: 'In-Person' },
        ],
      },
      {
        name: 'preferred_time_slot',
        label: 'Preferred Time Slot',
        type: 'select',
        required: true,
        options: [
          { value: 'morning', label: 'Morning (9 AM - 12 PM)' },
          { value: 'afternoon', label: 'Afternoon (12 PM - 4 PM)' },
          { value: 'evening', label: 'Evening (4 PM - 7 PM)' },
        ],
      },
      {
        name: 'available_days',
        label: 'Available Days (comma separated)',
        type: 'text',
        required: true,
        placeholder: 'e.g., Monday, Wednesday, Friday',
        helperText: 'List the days you are available for interview',
      },
      {
        name: 'special_requirements',
        label: 'Special Requirements or Notes',
        type: 'textarea',
        required: false,
        placeholder: 'Any special requirements or time constraints...',
      },
    ],
    documents: [
      {
        name: 'portfolio',
        label: 'Portfolio (Optional)',
        required: false,
        acceptedFormats: ['.pdf', '.zip'],
        maxSize: 10,
        description: 'Upload your work portfolio if applicable (max 10MB)',
      },
    ],
  },
  {
    name: 'academic',
    number: 3,
    title: 'Academic Information',
    description: 'Provide your academic credentials and documents.',
    fields: [
      {
        name: 'current_gpa',
        label: 'Current GPA/Percentage',
        type: 'text',
        required: true,
        placeholder: 'e.g., 3.8/4.0 or 85%',
      },
      {
        name: 'expected_graduation',
        label: 'Expected Graduation Date',
        type: 'date',
        required: true,
      },
      {
        name: 'relevant_coursework',
        label: 'Relevant Coursework',
        type: 'textarea',
        required: true,
        placeholder: 'List relevant courses you have completed...',
        helperText: 'List major courses related to this internship',
      },
      {
        name: 'academic_achievements',
        label: 'Academic Achievements',
        type: 'textarea',
        required: false,
        placeholder: 'Any awards, honors, or special recognitions...',
      },
    ],
    documents: [
      {
        name: 'transcripts',
        label: 'Academic Transcripts',
        required: true,
        acceptedFormats: ['.pdf'],
        maxSize: 5,
        description: 'Upload official or unofficial transcripts (max 5MB)',
      },
      {
        name: 'enrollment_certificate',
        label: 'Enrollment Certificate',
        required: true,
        acceptedFormats: ['.pdf'],
        maxSize: 2,
        description: 'Upload proof of current enrollment (max 2MB)',
      },
      {
        name: 'id_card',
        label: 'Student ID Card',
        required: true,
        acceptedFormats: ['.pdf', '.jpg', '.png'],
        maxSize: 2,
        description: 'Upload a copy of your student ID (max 2MB)',
      },
    ],
  },
  {
    name: 'financials',
    number: 4,
    title: 'Financial Information',
    description: 'Provide financial details and banking information.',
    fields: [
      {
        name: 'bank_account_name',
        label: 'Bank Account Holder Name',
        type: 'text',
        required: true,
        placeholder: 'As per bank records',
      },
      {
        name: 'bank_name',
        label: 'Bank Name',
        type: 'text',
        required: true,
        placeholder: 'e.g., State Bank of India',
      },
      {
        name: 'account_number',
        label: 'Account Number',
        type: 'text',
        required: true,
        placeholder: 'Your bank account number',
      },
      {
        name: 'ifsc_code',
        label: 'IFSC Code',
        type: 'text',
        required: true,
        placeholder: 'e.g., SBIN0001234',
      },
      {
        name: 'pancard_number',
        label: 'PAN Card Number',
        type: 'text',
        required: true,
        placeholder: 'e.g., ABCDE1234F',
      },
      {
        name: 'emergency_contact_name',
        label: 'Emergency Contact Name',
        type: 'text',
        required: true,
      },
      {
        name: 'emergency_contact_phone',
        label: 'Emergency Contact Phone',
        type: 'tel',
        required: true,
        placeholder: '+91-9876543210',
      },
      {
        name: 'emergency_contact_relation',
        label: 'Relationship to Emergency Contact',
        type: 'text',
        required: true,
        placeholder: 'e.g., Parent, Sibling',
      },
    ],
    documents: [
      {
        name: 'pan_card',
        label: 'PAN Card',
        required: true,
        acceptedFormats: ['.pdf', '.jpg', '.png'],
        maxSize: 2,
        description: 'Upload a clear copy of your PAN card (max 2MB)',
      },
      {
        name: 'cancelled_cheque',
        label: 'Cancelled Cheque / Bank Statement',
        required: true,
        acceptedFormats: ['.pdf', '.jpg', '.png'],
        maxSize: 2,
        description: 'Upload cancelled cheque or recent bank statement (max 2MB)',
      },
      {
        name: 'aadhar_card',
        label: 'Aadhar Card',
        required: true,
        acceptedFormats: ['.pdf', '.jpg', '.png'],
        maxSize: 2,
        description: 'Upload both sides of your Aadhar card (max 2MB)',
      },
    ],
  },
  {
    name: 'visa',
    number: 5,
    title: 'Visa & Travel Documents',
    description: 'Provide passport and visa information for international internships.',
    fields: [
      {
        name: 'passport_number',
        label: 'Passport Number',
        type: 'text',
        required: true,
        placeholder: 'e.g., A1234567',
      },
      {
        name: 'passport_issue_date',
        label: 'Passport Issue Date',
        type: 'date',
        required: true,
      },
      {
        name: 'passport_expiry_date',
        label: 'Passport Expiry Date',
        type: 'date',
        required: true,
      },
      {
        name: 'place_of_birth',
        label: 'Place of Birth',
        type: 'text',
        required: true,
        placeholder: 'City, Country',
      },
      {
        name: 'nationality',
        label: 'Nationality',
        type: 'text',
        required: true,
        placeholder: 'e.g., Indian',
      },
      {
        name: 'previous_visa',
        label: 'Have you had a visa before?',
        type: 'select',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'visa_rejection_history',
        label: 'Previous Visa Rejection',
        type: 'textarea',
        required: false,
        placeholder: 'If applicable, provide details of any previous visa rejections...',
      },
    ],
    documents: [
      {
        name: 'passport_copy',
        label: 'Passport Copy',
        required: true,
        acceptedFormats: ['.pdf', '.jpg', '.png'],
        maxSize: 5,
        description: 'Upload first and last page of passport (max 5MB)',
      },
      {
        name: 'passport_photo',
        label: 'Passport Size Photograph',
        required: true,
        acceptedFormats: ['.jpg', '.png'],
        maxSize: 1,
        description: 'Upload recent passport-size photo (max 1MB)',
      },
      {
        name: 'previous_visa_copy',
        label: 'Previous Visa Copy (if applicable)',
        required: false,
        acceptedFormats: ['.pdf', '.jpg', '.png'],
        maxSize: 3,
        description: 'Upload copy of previous visa if available (max 3MB)',
      },
    ],
  },
  {
    name: 'relocation',
    number: 6,
    title: 'Relocation & Accommodation',
    description: 'Provide information about your relocation and accommodation needs.',
    fields: [
      {
        name: 'current_location',
        label: 'Current Location',
        type: 'text',
        required: true,
        placeholder: 'City, State, Country',
      },
      {
        name: 'need_accommodation',
        label: 'Do you need accommodation assistance?',
        type: 'select',
        required: true,
        options: [
          { value: 'yes', label: 'Yes' },
          { value: 'no', label: 'No' },
        ],
      },
      {
        name: 'accommodation_preference',
        label: 'Accommodation Preference',
        type: 'select',
        required: false,
        options: [
          { value: 'shared', label: 'Shared Accommodation' },
          { value: 'private', label: 'Private Accommodation' },
          { value: 'hostel', label: 'Hostel' },
          { value: 'homestay', label: 'Homestay' },
        ],
      },
      {
        name: 'dietary_restrictions',
        label: 'Dietary Restrictions',
        type: 'text',
        required: false,
        placeholder: 'e.g., Vegetarian, Vegan, Allergies',
      },
      {
        name: 'medical_conditions',
        label: 'Medical Conditions',
        type: 'textarea',
        required: false,
        placeholder: 'Any medical conditions we should be aware of...',
        helperText: 'This information will be kept confidential',
      },
      {
        name: 'relocation_date',
        label: 'Preferred Relocation Date',
        type: 'date',
        required: true,
        helperText: 'When would you like to relocate?',
      },
      {
        name: 'additional_requirements',
        label: 'Additional Requirements',
        type: 'textarea',
        required: false,
        placeholder: 'Any other requirements or concerns regarding relocation...',
      },
    ],
    documents: [
      {
        name: 'medical_certificate',
        label: 'Medical Fitness Certificate',
        required: false,
        acceptedFormats: ['.pdf'],
        maxSize: 2,
        description: 'Upload medical fitness certificate if required (max 2MB)',
      },
      {
        name: 'local_address_proof',
        label: 'Current Address Proof',
        required: true,
        acceptedFormats: ['.pdf', '.jpg', '.png'],
        maxSize: 2,
        description: 'Upload current address proof (utility bill, etc.) (max 2MB)',
      },
    ],
  },
  {
    name: 'final_review',
    number: 7,
    title: 'Final Review & Declaration',
    description: 'Review all information and provide final declarations.',
    fields: [
      {
        name: 'how_did_you_hear',
        label: 'How did you hear about this internship?',
        type: 'select',
        required: true,
        options: [
          { value: 'website', label: 'Company Website' },
          { value: 'university', label: 'University/College' },
          { value: 'social_media', label: 'Social Media' },
          { value: 'friend', label: 'Friend/Referral' },
          { value: 'job_portal', label: 'Job Portal' },
          { value: 'other', label: 'Other' },
        ],
      },
      {
        name: 'motivation',
        label: 'Why do you want this internship?',
        type: 'textarea',
        required: true,
        placeholder: 'Tell us what motivates you to apply for this internship...',
        helperText: 'Minimum 200 characters',
      },
      {
        name: 'career_goals',
        label: 'Career Goals',
        type: 'textarea',
        required: true,
        placeholder: 'Describe your short-term and long-term career goals...',
        helperText: 'Minimum 100 characters',
      },
      {
        name: 'confirmation_accurate',
        label: 'I confirm that all information provided is accurate',
        type: 'select',
        required: true,
        options: [
          { value: 'yes', label: 'Yes, I confirm' },
        ],
      },
      {
        name: 'confirmation_terms',
        label: 'I agree to the terms and conditions',
        type: 'select',
        required: true,
        options: [
          { value: 'yes', label: 'Yes, I agree' },
        ],
      },
    ],
    documents: [
      {
        name: 'recommendation_letter',
        label: 'Letter of Recommendation (Optional)',
        required: false,
        acceptedFormats: ['.pdf'],
        maxSize: 3,
        description: 'Upload letter of recommendation from professor or employer (max 3MB)',
      },
      {
        name: 'additional_documents',
        label: 'Any Additional Documents',
        required: false,
        acceptedFormats: ['.pdf', '.doc', '.docx', '.zip'],
        maxSize: 10,
        description: 'Upload any other relevant documents (max 10MB)',
      },
    ],
  },
];

export function getStepConfig(stepName: ApplicationStepName): ApplicationStepConfig | undefined {
  return APPLICATION_STEPS.find(step => step.name === stepName);
}

export function getStepByNumber(stepNumber: number): ApplicationStepConfig | undefined {
  return APPLICATION_STEPS.find(step => step.number === stepNumber);
}
